In [ ]:
import kagglehub
import b as pd
import numpy as np
from pathlib import Path

path = Path(kagglehub.dataset_download("pavansubhasht/ibm-hr-analytics-attrition-dataset"))

csv_file = next(path.glob("*.csv"))
df = pd.read_csv(csv_file)

/home/hz/file/git/uiu-code-archive/AI_LAB/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
rows, cols = df.shape
print("rows:", rows)
print("cols:", cols)

rows: 1470
cols: 35

In [ ]:
df.describe(include='all')

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470,1470,1470.000000,1470,1470.000000,1470.000000,1470,1470.0,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
unique,NaN,2,3,NaN,3,NaN,NaN,6,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,No,Travel_Rarely,NaN,Research & Development,NaN,NaN,Life Sciences,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1233,1043,NaN,961,NaN,NaN,606,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,36.923810,NaN,NaN,802.485714,NaN,9.192517,2.912925,NaN,1.0,1024.865306,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,NaN,NaN,403.509100,NaN,8.106864,1.024165,NaN,0.0,602.024335,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,NaN,NaN,102.000000,NaN,1.000000,1.000000,NaN,1.0,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,NaN,NaN,465.000000,NaN,2.000000,2.000000,NaN,1.0,491.250000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,NaN,NaN,802.000000,NaN,7.000000,3.000000,NaN,1.0,1020.500000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,NaN,NaN,1157.000000,NaN,14.000000,4.000000,NaN,1.0,1555.750000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,NaN,NaN,1499.000000,NaN,29.000000,5.000000,NaN,1.0,2068.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [ ]:
missing = df.isnull().sum()
print(missing[missing > 0] if missing.any() else "None is missing...")

dups = df.duplicated().sum()
print("dups:", dups)

None is missing...
dups: 0

In [ ]:
for col in df.columns:
    if df[col].isnull().any():
        if pd.api.types.is_numeric_dtype(df[col]):
            fill_value = df[col].median()
        else:
            fill_value = df[col].mode()[0]

        df[col] = df[col].fillna(fill_value)

In [ ]:
df.drop_duplicates(inplace=True)
rows, cols = df.shape
print("rows:", rows)
print("cols:", cols)

rows: 1470
cols: 35

In [ ]:
# print(df.columns.tolist())
df.dropna(subset=['Attrition'], inplace=True)

In [ ]:
numeric_cols = df.select_dtypes(include=[np.number]).columns
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

rows, cols = df.shape
print("rows:", rows)
print("cols:", cols)

rows: 699
cols: 35

In [ ]:
cols = df.select_dtypes(include=['str']).columns

for col in cols:
    df[col] = df[col].str.lower()

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
2,37,yes,travel_rarely,1373,research & development,2,2,other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,no,travel_frequently,1392,research & development,3,4,life sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
5,32,no,travel_frequently,1005,research & development,2,2,life sciences,1,8,...,3,80,0,8,2,2,7,7,3,6
11,29,no,travel_rarely,153,research & development,15,2,life sciences,1,15,...,4,80,0,10,3,3,9,5,0,8
12,31,no,travel_rarely,670,research & development,26,1,life sciences,1,16,...,4,80,1,5,1,2,5,2,4,3

In [ ]:
Features = df.drop(columns='Attrition')
Labels = df[['Attrition']].replace({'no': 0, 'yes': 1})

print("Features:", Features.shape)
print("Labels:", Labels.shape)

Labels.head()

Features: (699, 34)
Labels: (699, 1)

   Attrition
2          1
3          0
5          0
11         0
12         0